name: ast_official
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basic packages
  cupertino_icons: ^1.0.6
  provider: ^6.1.5+1
  flutter_svg: ^2.0.10+1
  dio: ^5.9.0
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  sizer: ^3.1.3
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.3
  swipeable_button_view: ^0.0.2
  file_picker: ^8.0.4
  dotted_border: ^2.1.0
  fl_chart: ^0.67.0
  simple_circular_progress_bar: ^1.0.2
  flutter_secure_storage: ^10.0.0
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.1.0
  app_settings: ^7.0.0
  firebase_core: ^4.3.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1

  # ✅ FLUTTER LOCALIZATIONS
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true   # Enable L10n generation

  # Assets
  assets:
    - assets/images/
    - assets/svg/

  # Fonts
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900

# ✅ FLUTTER INTL PLUGIN CONFIGURATION
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: S
